time_service_uri: "http://onearth-time-service/time_service/time"
gc_service_uri: "http://onearth-capabilities/oe-status/gc"
tms_defs_file: "/etc/onearth/config/conf/tilematrixsets.xml"
layer_config_source: "/etc/onearth/config/layers/oe-status/"
apache_config_location: "/etc/httpd/conf.d/"
base_uri_gc: "http://localhost/oe-status"
base_uri_gts: "http://localhost/oe-status"
base_uri_meta: "https://gibs.earthdata.nasa.gov"
epsg_code: "EPSG:4326"
gc_service:
  internal_endpoint: "/var/www/html/oe-status"
  external_endpoint: "/oe-status/gc"
  config_prefix: "oe-status_gc_service"
  gc_header_file: "/etc/onearth/config/conf/header_gc.xml"
  gts_header_file: "/etc/onearth/config/conf/header_gts.xml"
  twms_gc_header_file: "/etc/onearth/config/conf/header_twms_gc.xml"
wmts_service:
  internal_endpoint: "/var/www/html/oe-status"
  external_endpoint: "/oe-status"
  config_prefix: "oe-status"
twms_service:
  internal_endpoint: "/var/www/html/oe-status"
  external_endpoint: "/oe-status"