layer_id: "AMSRU2_Soil_Moisture_NPD_Day"
layer_title: "Soil Moisture (Normalized Polarization Difference, Day, v2, Near Real-Time, AMSR2, GCOM-W1)"
layer_name: "AMSRU2_Soil_Moisture_NPD_Day tileset"
projection: "EPSG:4326"
tilematrixset: "2km"
mime_type: "image/png"
static: false
abstract: "AMSRU2_Soil_Moisture_NPD_Day abstract"
metadata:
  - {"xlink:type": "simple", "xlink:role": "http://earthdata.nasa.gov/gibs/metadata-type/colormap", "xlink:href": "{base_uri_meta}/colormaps/v1.3/AMSRU2_Soil_Moisture_NPD_Day.xm", "xlink:title": "GIBS Color Map: Data - RGB Mapping"}
  - {"xlink:type": "simple", "xlink:role": "http://earthdata.nasa.gov/gibs/metadata-type/colormap/1.0", "xlink:href": "{base_uri_meta}/colormaps/v1.0/AMSRU2_Soil_Moisture_NPD_Day.xm", "xlink:title": "GIBS Color Map: Data - RGB Mapping"}
  - {"xlink:type": "simple", "xlink:role": "http://earthdata.nasa.gov/gibs/metadata-type/colormap/1.2", "xlink:href": "{base_uri_meta}/colormaps/v1.2/AMSRU2_Soil_Moisture_NPD_Day.xm", "xlink:title": "GIBS Color Map: Data - RGB Mapping"}
  - {"xlink:type": "simple", "xlink:role": "http://earthdata.nasa.gov/gibs/metadata-type/colormap/1.3", "xlink:href": "{base_uri_meta}/colormaps/v1.3/AMSRU2_Soil_Moisture_NPD_Day.xm", "xlink:title": "GIBS Color Map: Data - RGB Mapping"}
source_mrf:
  size_x: 20480
  size_y: 10240
  bands: 1
  tile_size_x: 512
  tile_size_y: 512
  idx_path: "/onearth/idx/epsg4326"
  data_file_uri: "{S3_URL}/epsg4326"
  year_dir: true
  bbox: -180,-90,180,90
  empty_tile: "/etc/onearth/empty_tiles/Blank_RGBA_512.png"