layer_id: "MODIS_Aqua_Brightness_Temp_Band31_Day"
layer_title: "Brightness Temperature (Band31, Day, v6, Standard, MODIS, Aqua)"
layer_name: "MODIS_Aqua_Brightness_Temp_Band31_Day tileset"
projection: "EPSG:4326"
tilematrixset: "1km"
mime_type: "image/jpeg"
static: false
abstract: "MODIS_Aqua_Brightness_Temp_Band31_Day abstract"
time_config:
  - "2000-01-01/2009-12-31/P1D"
  - "2011-01-01/2017-06-04/P1D"
  - "2017-06-20/DETECT/P1D"
best_config:
  1: "MODIS_Aqua_Brightness_Temp_Band31_Day_v5_NRT"
  2: "MODIS_Aqua_Brightness_Temp_Band31_Day_v5_STD"
  3: "MODIS_Aqua_Brightness_Temp_Band31_Day_v6_NRT"
  4: "MODIS_Aqua_Brightness_Temp_Band31_Day_v6_STD"
metadata:
  - {"xlink:type": "simple", "xlink:role": "http://earthdata.nasa.gov/gibs/metadata-type/colormap", "xlink:href": "{base_uri_meta}/colormaps/v1.3/MODIS_Aqua_Brightness_Temp_Band31_Day.xml", "xlink:title": "GIBS Color Map: Data - RGB Mapping"}
  - {"xlink:type": "simple", "xlink:role": "http://earthdata.nasa.gov/gibs/metadata-type/colormap/1.0", "xlink:href": "{base_uri_meta}/colormaps/v1.0/MODIS_Aqua_Brightness_Temp_Band31_Day.xml", "xlink:title": "GIBS Color Map: Data - RGB Mapping"}
  - {"xlink:type": "simple", "xlink:role": "http://earthdata.nasa.gov/gibs/metadata-type/colormap/1.3", "xlink:href": "{base_uri_meta}/colormaps/v1.3/MODIS_Aqua_Brightness_Temp_Band31_Day.xml", "xlink:title": "GIBS Color Map: Data - RGB Mapping"}
source_mrf:
  size_x: 40960
  size_y: 20480
  bands: 4
  tile_size_x: 512
  tile_size_y: 512
  idx_path: "/onearth/idx/epsg4326"
  data_file_uri: "{S3_URL}/epsg4326"
  year_dir: true
  bbox: -180,-90,180,90
  empty_tile: "/etc/onearth/empty_tiles/Blank_RGBA_512.png"